Repository kushthedude/CV-BUILDER, pull requests merged in 2019-05, with the labels that each got.

#2 Add a Codacy badge to README.md
  README.md
Labels: good first issue

#3 fix: Readme updation
  README.md
Labels: fix

#5 feat: Removing Two Codacy Badges
  README.md
Labels: feature
